version: "3.8"

services:
  api:
    image: ghcr.io/ragheria/cnadv-playwright-api:latest
    environment:
      - DATAJURI_EMAIL=${DATAJURI_EMAIL}
      - DATAJURI_PASSWORD=${DATAJURI_PASSWORD}
      - PORT=3001
      - NODE_ENV=production
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == manager01
      resources:
        limits:
          memory: 800m
        reservations:
          memory: 400m
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    external: true
